"""empty message

Revision ID: 99183fc5f68c
Revises: 58ea547e99e1
Create Date: 2023-01-26 19:38:02.275268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99183fc5f68c'
down_revision = '58ea547e99e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('breed', sa.String(length=250), nullable=False),
    sa.Column('sterilized', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    # ### end Alembic commands ###
